// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/games/AuraQuizGame.tsx": () => import("../components/mockups/games/AuraQuizGame.tsx"),
  "./components/mockups/games/HeartmatchGame.tsx": () => import("../components/mockups/games/HeartmatchGame.tsx"),
  "./components/mockups/games/WordRizzGame.tsx": () => import("../components/mockups/games/WordRizzGame.tsx")
};
